export const AUTH_LOGIN_REQUEST = 'AUTH_LOGIN_REQUEST';
export const AUTH_LOGIN_SUCCES = 'AUTH_LOGIN_SUCCES';
export const AUTH_LOGIN_FAILURE = 'AUTH_LOGIN_FAILURE';

export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const ADVERT_LOADED_SUCCES = 'ADVERT_LOADED_SUCCES';

export const ADVERTS_LOADED_SUCCES = 'ADVERTS_LOADED_SUCCES';
export const ADVERTS_CREATED_SUCCES = 'ADVERTS_CREATED_SUCCES';

export const UI_RESET_ERROR = "UI_RESET_ERROR"